In [6]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [7]:
df=pd.read_csv("iris.csv")

In [8]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
X=df.drop(['species'],axis=1)
Y=df['species']


In [152]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=9)

In [153]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [154]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [155]:
X_train

array([[ 1.11468068, -0.16853223,  0.94458035,  1.15035371],
       [ 0.13023408, -0.16853223,  0.54242754,  0.74906753],
       [-0.97726834,  0.5055967 , -1.23853491, -0.98983924],
       [-0.11587757, -0.84266117,  0.14027473, -0.32102894],
       [-0.23893339, -1.06737081, -0.20442768, -0.32102894],
       [-0.11587757, -0.84266117,  0.02537393, -0.05350482],
       [ 1.11468068, -0.61795152,  0.54242754,  0.21401929],
       [-1.34643582, -0.16853223, -1.41088611, -1.25736335],
       [ 1.60690398,  1.17972564,  1.28928276,  1.68540194],
       [-1.10032417,  0.73030635, -1.35343571, -1.39112541],
       [-0.97726834,  0.95501599, -1.41088611, -1.25736335],
       [ 0.49940156,  0.5055967 ,  1.23183236,  1.68540194],
       [ 0.99162486,  0.05617741,  0.48497714,  0.34778135],
       [-0.97726834,  1.62914493, -1.12363411, -1.1236013 ],
       [ 0.49940156, -0.39324188,  1.00203076,  0.74906753],
       [ 0.37634573, -1.96620939,  0.37007634,  0.34778135],
       [-1.59254747,  0.

In [156]:
X_test

array([[ 2.44064866,  0.08233353,  1.53718068,  1.60493353],
       [-0.16586933, -1.01544685,  0.57996194,  0.21117546],
       [ 1.25586776,  0.08233353,  1.03041782,  1.60493353],
       [ 1.01891157,  0.08233353,  1.03041782,  1.22481769],
       [-0.75825978, -2.66211743,  0.07319908, -0.04223509],
       [-0.87673787,  0.35677862, -1.05294061, -1.1825826 ],
       [-0.75825978,  1.18011391, -0.99663363, -0.80246676],
       [-1.23217214,  0.35677862, -1.05294061, -1.05587732],
       [ 1.13738966,  0.08233353,  0.57996194,  0.46458602],
       [-0.87673787,  0.35677862, -1.05294061, -1.1825826 ],
       [-0.75825978,  0.08233353, -0.99663363, -1.05587732],
       [ 0.54499921, -0.46655666,  0.7488829 ,  0.21117546],
       [-0.63978169, -1.28989195, -0.20833584,  0.08447019],
       [-0.04739124, -0.74100176,  0.46734797,  0.33788074],
       [-0.63978169,  1.18011391, -1.05294061, -1.05587732],
       [-0.16586933, -1.56433704,  0.18581305, -0.04223509],
       [-0.28434742,  1.

In [157]:
GNB=GaussianNB()
GNB.fit(X_train,Y_train)

GaussianNB()

In [158]:
Y_test_pred=GNB.predict(X_test)
Y_test_pred

array(['virginica', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'virginica'], dtype='<U10')

In [159]:
confusion_matrix(Y_test,Y_test_pred)

array([[12,  1,  0],
       [ 0,  8,  1],
       [ 0,  0,  8]], dtype=int64)

In [160]:
print(classification_report(Y_test,Y_test_pred))

              precision    recall  f1-score   support

      setosa       1.00      0.92      0.96        13
  versicolor       0.89      0.89      0.89         9
   virginica       0.89      1.00      0.94         8

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.94      0.93      0.93        30



In [161]:
print("accuarcy:",accuracy_score(Y_test,Y_test_pred))

accuarcy: 0.9333333333333333
